"""add_hashed_password_to_users

Revision ID: 5061722e8413
Revises: 4f110b38f693
Create Date: 2026-06-25 09:38:04.712008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5061722e8413'
down_revision: Union[str, Sequence[str], None] = '4f110b38f693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))

    users = sa.table(
        'users',
        sa.column('hashed_password', sa.String()),
    )
    op.execute(
        users.update()
        .where(users.c.hashed_password.is_(None))
        .values(hashed_password='dev-placeholder-password-hash')
    )

    op.alter_column('users', 'hashed_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
